ARG BUILD_FROM
FROM ${BUILD_FROM}

WORKDIR /data

# Install system
RUN apk update && apk add --no-cache \
    npm=12.15.0-r1 \
    nodejs=12.15.0-r1 

# Build arugments
ARG BUILD_ARCH=amd64
ARG BUILD_VERSION=dev

VOLUME /data

# Labels
LABEL \
    io.hass.name="Walleon" \
    io.hass.description="Control panel for Home Assistant" \
    io.hass.arch="${BUILD_ARCH}" \
    io.hass.type="addon" \
    io.hass.version=${BUILD_VERSION} \